include: https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml

test:1.5:
    extends:
        - .julia:1.5
        - .test
    tags:
        - nvidia
        - latest
    only:
        variables:
            - $CI_COMMIT_TITLE =~ /\[ci\]/
